insert into dictionary (value,word) values ('당신은 나의 0순위','0000');
insert into dictionary (value,word) values ('영원히 변하지 말자','0001');
insert into dictionary (value,word) values ('외로워','0001000');
insert into dictionary (value,word) values ('손가락 욕','00100');
insert into dictionary (value,word) values ('good night kiss','0011');
insert into dictionary (value,word) values ('영원히','012');
insert into dictionary (value,word) values ('영원히 사랑해','0024');
insert into dictionary (value,word) values ('땡땡이 치자','0027');
insert into dictionary (value,word) values ('차에 문제가 생겼어','0049');
insert into dictionary (value,word) values ('가고 있는 중이야','0090');
insert into dictionary (value,word) values ('조금 늦어','0098');
insert into dictionary (value,word) values ('응','010');
insert into dictionary (value,word) values ('돌아와','0100');
insert into dictionary (value,word) values ('시간 지켜','0116');
insert into dictionary (value,word) values ('영원히 사랑해','0124');
insert into dictionary (value,word) values ('영원한 친구','0179');
insert into dictionary (value,word) values ('영원한 친구 사이','017942');
insert into dictionary (value,word) values ('연인 사이','0242');
insert into dictionary (value,word) values ('많이 아파','0285');
insert into dictionary (value,word) values ('영원히 사랑해','04');
insert into dictionary (value,word) values ('영원히 사랑해','0404');
insert into dictionary (value,word) values ('영화 보러 가자','04290');
insert into dictionary (value,word) values ('빵 사와','0455');
insert into dictionary (value,word) values ('Hello','07734');
insert into dictionary (value,word) values ('모든 것이 취소됐다(빵구빵구)','0909');
insert into dictionary (value,word) values ('볼링장 가자','0929');
insert into dictionary (value,word) values ('돌아와','100');
insert into dictionary (value,word) values ('네가 그리워','10000001');
insert into dictionary (value,word) values ('만세','100003');
insert into dictionary (value,word) values ('많이 사랑해','100024');
insert into dictionary (value,word) values ('천사','1004');
insert into dictionary (value,word) values ('고민스러워','1008');
insert into dictionary (value,word) values ('열렬히 사모한다','1010235');
insert into dictionary (value,word) values ('기분 좋아','101101');
insert into dictionary (value,word) values ('열이 펄펄','10288');
insert into dictionary (value,word) values ('러브(LOVE)','1052');
insert into dictionary (value,word) values ('고민이야','108');
insert into dictionary (value,word) values ('흥','11010');
insert into dictionary (value,word) values ('흐흐','11011101');
insert into dictionary (value,word) values ('비상사태','1111');
insert into dictionary (value,word) values ('긴급상황','112');
insert into dictionary (value,word) values ('가운데에 선을 그으면 사랑해로 읽힌다','1126611');
insert into dictionary (value,word) values ('I miss you','1177155400');
insert into dictionary (value,word) values ('일을 빨리 해라','1182');
insert into dictionary (value,word) values ('병원이야','119');
insert into dictionary (value,word) values ('지금 바빠','1200');
insert into dictionary (value,word) values ('홀짝홀짝(술 마시자)','1212');
insert into dictionary (value,word) values ('이리 오소','1254');
insert into dictionary (value,word) values ('이리 오시오','1255');
insert into dictionary (value,word) values ('이리 오십사','12504');
insert into dictionary (value,word) values ('일이 발생','1283');
insert into dictionary (value,word) values ('난 지금 몸이 아파','129129');
insert into dictionary (value,word) values ('기분 완전 좋아','13486');
insert into dictionary (value,word) values ('너 없이 못 살아','1350');
insert into dictionary (value,word) values ('정말 이상하다','13579');
insert into dictionary (value,word) values ('1년 365일 24시간 사랑해','1365244');
insert into dictionary (value,word) values ('식사나 함께 합시다','1414');
insert into dictionary (value,word) values ('일사천리','1472');
insert into dictionary (value,word) values ('사랑해','1486');
insert into dictionary (value,word) values ('일찍 와','1717');
insert into dictionary (value,word) values ('I LOVE YOU','17171771');
insert into dictionary (value,word) values ('일찍 일찍 와','17175');
insert into dictionary (value,word) values ('일찍 일찍 일어나','171715');
insert into dictionary (value,word) values ('일찍 오렴','1750');
insert into dictionary (value,word) values ('씨발씨발','1818');
insert into dictionary (value,word) values ('나 너 싫어','186');
insert into dictionary (value,word) values ('집에 급한 일','1919');
insert into dictionary (value,word) values ('그럼 이만','20000');
insert into dictionary (value,word) values ('천사에게','21004');
insert into dictionary (value,word) values ('이...(불만)','2222');
insert into dictionary (value,word) values ('둘이서 만나자','2241000045');
insert into dictionary (value,word) values ('이상無','230');
insert into dictionary (value,word) values ('이리 와','2255');
insert into dictionary (value,word) values ('짝짝짝짝','2468');
insert into dictionary (value,word) values ('잘가','258');
insert into dictionary (value,word) values ('이륙이륙','2626');
insert into dictionary (value,word) values ('가족 중에 축하해 줄 사람이 있어','2715');
insert into dictionary (value,word) values ('할 얘기 있어','2828');
insert into dictionary (value,word) values ('이제 그만 만나','2848');
insert into dictionary (value,word) values ('이그 이그!','2929');
insert into dictionary (value,word) values ('용기를 잃지 마','3232');
insert into dictionary (value,word) values ('차 막혀','3255');
insert into dictionary (value,word) values ('심심해','331');
insert into dictionary (value,word) values ('심심하니 영화 보러 가자','3312042');
insert into dictionary (value,word) values ('보고 싶어','3322');
insert into dictionary (value,word) values ('힘내라','337');
insert into dictionary (value,word) values ('사무치게 그리워','3575');
insert into dictionary (value,word) values ('자주 연락해','4242');
insert into dictionary (value,word) values ('사랑사랑','4343');
insert into dictionary (value,word) values ('死死死死','4444');
insert into dictionary (value,word) values ('사아아라아앙해애애','444888666');
insert into dictionary (value,word) values ('죽도록 사랑해','4486');
insert into dictionary (value,word) values ('사랑해','486');
insert into dictionary (value,word) values ('우리 사랑은 영원할 거야','4860');
insert into dictionary (value,word) values ('사고 났으니 빨리와','494982535');
insert into dictionary (value,word) values ('오직 너만 사랑해','504');
insert into dictionary (value,word) values ('S.O.S','505');
insert into dictionary (value,word) values ('오늘 밤 전화해','5091');
insert into dictionary (value,word) values ('조금 늦어','51055');
insert into dictionary (value,word) values ('만났던 곳에서 기다릴게','5111');
insert into dictionary (value,word) values ('항상 널 생각하고 있을게','5112');
insert into dictionary (value,word) values ('오늘 술 한잔하자','5121');
insert into dictionary (value,word) values ('하트','514709635');
insert into dictionary (value,word) values ('기름이 떨어졌다','5151');
insert into dictionary (value,word) values ('오늘은 잊을 수 없는 날이야','5200');
insert into dictionary (value,word) values ('우리 만나자','521000045');
insert into dictionary (value,word) values ('보고 싶다','522');
insert into dictionary (value,word) values ('우리 사귀자','5222');
insert into dictionary (value,word) values ('다 줄게','535');
insert into dictionary (value,word) values ('카운트다운','54321');
insert into dictionary (value,word) values ('오빠 사랑해','5454');
insert into dictionary (value,word) values ('보고 싶어','55102');
insert into dictionary (value,word) values ('잘 살아라','552111152');
insert into dictionary (value,word) values ('오오사랑','5543');
insert into dictionary (value,word) values ('증오','5555');
insert into dictionary (value,word) values ('오~','55555555');
insert into dictionary (value,word) values ('오빠를 사랑하는 사람','5844');
insert into dictionary (value,word) values ('오빠 사랑해','5854');
insert into dictionary (value,word) values ('오빠 빨리','5882');
insert into dictionary (value,word) values ('우리 집으로 와','6288');
insert into dictionary (value,word) values ('보고 싶다','6515');
insert into dictionary (value,word) values ('보고 싶다','6516');
insert into dictionary (value,word) values ('뽀뽀','660660');
insert into dictionary (value,word) values ('삐삐 쳐','6616617');
insert into dictionary (value,word) values ('축하해','7115');
insert into dictionary (value,word) values ('오늘 휴강이야','7116');
insert into dictionary (value,word) values ('친한 사이','7142');
insert into dictionary (value,word) values ('축하해 주셔서 감사합니다','7175');
insert into dictionary (value,word) values ('친한 친구','7179');
insert into dictionary (value,word) values ('친한 친구 사이','717942');
insert into dictionary (value,word) values ('오늘 미팅한다','7205');
insert into dictionary (value,word) values ('호출해라','7272');
insert into dictionary (value,word) values ('죽도록 사랑해','7486');
insert into dictionary (value,word) values ('싫어','75');
insert into dictionary (value,word) values ('착륙 착륙','7676');
insert into dictionary (value,word) values ('드라이브 하자','7700');
insert into dictionary (value,word) values ('우는 소리','777');
insert into dictionary (value,word) values ('친구야 힘내','79337');
insert into dictionary (value,word) values ('친구사이','7942');
insert into dictionary (value,word) values ('바보','8080');
insert into dictionary (value,word) values ('빨리와','820');
insert into dictionary (value,word) values ('약속장소도착','8200');
insert into dictionary (value,word) values ('빨리 와','825');
insert into dictionary (value,word) values ('빨리 만나자','82504');
insert into dictionary (value,word) values ('빨리 오시오','82515');
insert into dictionary (value,word) values ('빨리 와','8255');
insert into dictionary (value,word) values ('굿모닝','952');
insert into dictionary (value,word) values ('빨리빨리','8282');
insert into dictionary (value,word) values ('파이팅','827');
insert into dictionary (value,word) values ('빨리 출발','8278');
insert into dictionary (value,word) values ('빨리빨리 집으로','8282755');
insert into dictionary (value,word) values ('빨리 가','8290');
insert into dictionary (value,word) values ('바로 출발','8578');
insert into dictionary (value,word) values ('바로바로 와요','858555');
insert into dictionary (value,word) values ('빠이빠이','882882');
insert into dictionary (value,word) values ('나 팔팔해','8888');
insert into dictionary (value,word) values ('집에 가','90');
insert into dictionary (value,word) values ('GO','9090');
insert into dictionary (value,word) values ('구질구질','9797');
insert into dictionary (value,word) values ('급한일','981');
insert into dictionary (value,word) values ('굿바이','982');
insert into dictionary (value,word) values ('할 이야기가 너무 많다(구구절절)','9977');
insert into dictionary (value,word) values ('행운을 빌어','9999');


-- insert into User (authority,fcm_token,password,phone_number) values ("ROLE_USER","string","$2a$10$PZksvg1TXbZgVQOZ/gZA0uk/NNfqmzGKXIrmuorv0Wn3A7Zyd2A5G","01012345678");
-- insert into user(phone_number, password, authority, fcm_token) values ("01050123883", "$2a$10$9r/Io6GJbIFtcY7x/d7.b.s6ZiOM6kTPzhzgKYaqUTxgAgt4lMZ5O", "ROLE_ADMIN", "0");